<?php

use Sx\Template\Template\Section\SectionInterface;
use Sx\Template\Template\Template;
use Sx\Template\Template\Text\TextInterface;
use Sx\Template\Template\Title\TitleInterface;

Template::get(TitleInterface::class)->set('Beispiel-Seite');

?>
<!doctype html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= Template::get(TitleInterface::class)->title() ?></title>
</head>
<body>
    <h1><?= Template::get(TitleInterface::class)->title() ?></h1>
    <?= Template::get(TextInterface::class)->text('introduction', 'Einleitung') ?>
    <?= Template::get(TextInterface::class)->text('content', 'Inhalt') ?>
    <h2><?= Template::get(SectionInterface::class)->section('Impressum') ?></h2>
    <?= Template::get(TextInterface::class)->text('imprint', 'Impressum') ?>
</body>
</html>
